import Head from 'next/head'
import AppBar from '../components/AppBar'

export default function Home() {

  let date = new Date()
  
  function getNbJours(date){
    return new Date(date.getFullYear(), date.getMonth()+1, -1).getDate()+1;
  }

  return (

    <div className='flex flex-col'>

      <Head>
        <title>Campus Riera - BDE</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <AppBar/>

      <div className="flex flex-col h-[60vh] bg-[url('/img/368947.webp')] bg-cover bg-center">

        <p></p>

      </div>

      <div className='border border-black flex flex-col gap-4 py-4'>

        <p className='flex flex-col px-4 text-xs border text-black border-black py-2 mx-4 h-10 items-center justify-center rounded-lg'>Calendrier de l&apos;année {date.getFullYear().toString()} - {(date.getFullYear()+1).toString()}</p>

        <div className={`grid grid-cols-7 px-4 gap-4 text-black text-center`}>

          <div className='flex flex-col text-xs border border-black py-2 px-4 rounded-lg h-10 items-center justify-center'>Lundi</div>
          <div className='flex flex-col text-xs border border-black py-2 px-4 rounded-lg h-10 items-center justify-center'>Mardi</div>
          <div className='flex flex-col text-xs border border-black py-2 px-4 rounded-lg h-10 items-center justify-center'>Mercredi</div>
          <div className='flex flex-col text-xs border border-black py-2 px-4 rounded-lg h-10 items-center justify-center'>Jeudi</div>
          <div className='flex flex-col text-xs border border-black py-2 px-4 rounded-lg h-10 items-center justify-center'>Vendredi</div>
          <div className='flex flex-col text-xs border border-black py-2 px-4 rounded-lg h-10 items-center justify-center'>Samedi</div>
          <div className='flex flex-col text-xs border border-black py-2 px-4 rounded-lg h-10 items-center justify-center'>Dimanche</div>

        </div>

        <div className={`grid grid-cols-7 px-4 gap-4 text-black text-center`}>

          {[...Array(getNbJours(date))].map((e,i)=>
            <p className='text-xs bg-gray-200 py-2 px-4 rounded-lg h-10'></p>
          )}

        </div>

      </div>

      <p>sc svdkjsnvdjsndvkns sod nsod no i oihoihoiho ihoihoiho ihoih oihoihiuhigyt-(r-f iuittu uhgiuhiug uiyu</p>
      <p>sc svdkjsnvdjsndvkns sod nsod no i oihoihoiho ihoihoiho ihoih oihoihiuhigyt-(r-f iuittu uhgiuhiug uiyu</p>
      <p>sc svdkjsnvdjsndvkns sod nsod no i oihoihoiho ihoihoiho ihoih oihoihiuhigyt-(r-f iuittu uhgiuhiug uiyu</p>
      <p>sc svdkjsnvdjsndvkns sod nsod no i oihoihoiho ihoihoiho ihoih oihoihiuhigyt-(r-f iuittu uhgiuhiug uiyu</p>
      <p>sc svdkjsnvdjsndvkns sod nsod no i oihoihoiho ihoihoiho ihoih oihoihiuhigyt-(r-f iuittu uhgiuhiug uiyu</p>
      <p>sc svdkjsnvdjsndvkns sod nsod no i oihoihoiho ihoihoiho ihoih oihoihiuhigyt-(r-f iuittu uhgiuhiug uiyu</p>
      <p>sc svdkjsnvdjsndvkns sod nsod no i oihoihoiho ihoihoiho ihoih oihoihiuhigyt-(r-f iuittu uhgiuhiug uiyu</p>
      <p>sc svdkjsnvdjsndvkns sod nsod no i oihoihoiho ihoihoiho ihoih oihoihiuhigyt-(r-f iuittu uhgiuhiug uiyu</p>
      <p>sc svdkjsnvdjsndvkns sod nsod no i oihoihoiho ihoihoiho ihoih oihoihiuhigyt-(r-f iuittu uhgiuhiug uiyu</p>
      <p>sc svdkjsnvdjsndvkns sod nsod no i oihoihoiho ihoihoiho ihoih oihoihiuhigyt-(r-f iuittu uhgiuhiug uiyu</p>
      <p>sc svdkjsnvdjsndvkns sod nsod no i oihoihoiho ihoihoiho ihoih oihoihiuhigyt-(r-f iuittu uhgiuhiug uiyu</p>
      <p>sc svdkjsnvdjsndvkns sod nsod no i oihoihoiho ihoihoiho ihoih oihoihiuhigyt-(r-f iuittu uhgiuhiug uiyu</p>
      <p>sc svdkjsnvdjsndvkns sod nsod no i oihoihoiho ihoihoiho ihoih oihoihiuhigyt-(r-f iuittu uhgiuhiug uiyu</p>
      <p>sc svdkjsnvdjsndvkns sod nsod no i oihoihoiho ihoihoiho ihoih oihoihiuhigyt-(r-f iuittu uhgiuhiug uiyu</p>
      <p>sc svdkjsnvdjsndvkns sod nsod no i oihoihoiho ihoihoiho ihoih oihoihiuhigyt-(r-f iuittu uhgiuhiug uiyu</p>
      <p>sc svdkjsnvdjsndvkns sod nsod no i oihoihoiho ihoihoiho ihoih oihoihiuhigyt-(r-f iuittu uhgiuhiug uiyu</p>
      <p>sc svdkjsnvdjsndvkns sod nsod no i oihoihoiho ihoihoiho ihoih oihoihiuhigyt-(r-f iuittu uhgiuhiug uiyu</p>
      <p>sc svdkjsnvdjsndvkns sod nsod no i oihoihoiho ihoihoiho ihoih oihoihiuhigyt-(r-f iuittu uhgiuhiug uiyu</p>
      <p>sc svdkjsnvdjsndvkns sod nsod no i oihoihoiho ihoihoiho ihoih oihoihiuhigyt-(r-f iuittu uhgiuhiug uiyu</p>
      <p>sc svdkjsnvdjsndvkns sod nsod no i oihoihoiho ihoihoiho ihoih oihoihiuhigyt-(r-f iuittu uhgiuhiug uiyu</p>
      <p>sc svdkjsnvdjsndvkns sod nsod no i oihoihoiho ihoihoiho ihoih oihoihiuhigyt-(r-f iuittu uhgiuhiug uiyu</p>
      <p>sc svdkjsnvdjsndvkns sod nsod no i oihoihoiho ihoihoiho ihoih oihoihiuhigyt-(r-f iuittu uhgiuhiug uiyu</p>

    </div>

  )

}
